name: rdemo
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - git
  - ipympl
  - numpy
  - scipy
  - sympy
  - matplotlib
  - pinocchio
  - qpsolvers
  - robot_descriptions
  #- crocoddyl not on windows, uncomment when moving to wsl
  - setuptools=81
  - trimesh
  - pyglet<2
  - rtree
  - pip:
    - networkx
    - pyserial
    - jsonpickle
    - git+https://github.com/meshcat-dev/meshcat-python.git
    - git+https://github.com/stephane-caron/meshcat-shapes.git
    #- ompl Also not on windows
