
class PrimaryStyle(object):
    PRIMARY_COLOR = '#293438'
    SECONDARY_COLOR = '#1d2429'
    TETRARY_COLOR = '#CC5500'
    QUATERNARY_COLOR = '#0055CC'

    SELECT_COLOR = TETRARY_COLOR

    DEBUG_COLOR = '#FF00FF'

    GENERAL_PADDING = 10

    MAIN_FRAME_PAD = 20

    HOME_BTN_SIZE = 90
    HOME_BTN_PADX = 20
    HOME_BTN_PADY = 0

    FONT_COLOR = '#FFFFFF'

    HL_BACKGROUND_COL = '#FFFFFF'
    HL_BACKGROUND_THICKNESS = 0
